RULE_CONFIG = {
    "risk_level": {"low_max": 3, "medium_max": 7},
    "attention_window": {
        "start_hour": 0,
        "end_hour": 5,
        "start_minute": 1,
        "end_minute": 300,
        "label": "00:01-05:00",
    },
    "late_input_max_days": 1,
    "late_input_score": {
        "transfer": {"low_after_days": 3, "medium_after_days": 4, "high_after_days": 8, "low_score": 1, "medium_score": 2, "high_score": 4},
        "tunai": {"low_after_days": 3, "medium_after_days": 4, "high_after_days": 8, "low_score": 1, "medium_score": 2, "high_score": 4},
    },
    "split_window_hours": 6,
    "split_threshold": 10_000_000,
    "amount_tolerance": 0.0,
    "score": {
        "off_hour": 1,
        "pre_payment_input": 2,
        "late_input_transfer": 2,
        "late_input_cash": 2,
        "date_mismatch": 1,
        "amount_mismatch": 4,
        "split_txn": 2,
    },
    "rules": {
        "off_hour": {
            "category": "Indikator Waktu",
            "name": "Input transaksi pada rentang waktu tertentu",
            "definition": "Penginputan transaksi pada rentang waktu tertentu perlu menjadi perhatian khusus sesuai matriks skor FEWS.",
            "description": "Input pada jam tidak normal menjadi perhatian khusus.",
            "recommendation": "Klarifikasi alasan input di rentang waktu perhatian dan pertimbangkan pembatasan input pada jam tertentu.",
            "clarification_required": True,
        },
        "pre_payment_input": {
            "category": "Indikator Waktu",
            "name": "Input sebelum transfer terjadi",
            "definition": "Penginputan transaksi harus dilakukan setelah pembayaran/transfer diterima.",
            "description": "Input mendahului tanggal/waktu pembayaran atau transfer.",
            "recommendation": "Minta bukti transfer dan koreksi tanggal input jika terjadi kesalahan.",
            "clarification_required": True,
        },
        "late_input_transfer": {
            "category": "Indikator Waktu",
            "name": "Keterlambatan input data setor transfer",
            "definition": "Keterlambatan input data setoran setelah transaksi diinput dinilai bertingkat: 3 hari, 4-7 hari, dan lebih dari 8 hari.",
            "description": "Input transfer melewati batas waktu data setoran.",
            "recommendation": "Klarifikasi penyebab keterlambatan transfer dan dokumentasikan pengecualian hari libur/bank tutup jika ada.",
            "clarification_required": True,
        },
        "late_input_cash": {
            "category": "Indikator Waktu",
            "name": "Keterlambatan input setoran tunai ke bank",
            "definition": "Keterlambatan input data setoran setelah transaksi diinput dinilai bertingkat: 3 hari, 4-7 hari, dan lebih dari 8 hari.",
            "description": "Input setoran tunai melewati batas waktu data setoran.",
            "recommendation": "Klarifikasi tanggal setor tunai ke bank dan alasan keterlambatan input.",
            "clarification_required": True,
        },
        "date_mismatch": {
            "category": "Indikator Waktu",
            "name": "Tanggal tidak konsisten pada data setoran",
            "definition": "Tanggal transaksi, tanggal input, tanggal setoran, dan tanggal bank harus konsisten.",
            "description": "Tanggal pada data setoran tidak selaras.",
            "recommendation": "Bandingkan data SIL dengan bukti transaksi dan lakukan koreksi melalui mekanisme audit trail.",
            "clarification_required": True,
        },
        "amount_mismatch": {
            "category": "Indikator Nilai Transaksi",
            "name": "Jumlah biaya tidak sesuai jumlah setor",
            "definition": "Jumlah biaya pada SIL harus sesuai dengan jumlah setor; selisih dapat mengindikasikan salah input atau double input.",
            "description": "Jumlah biaya berbeda dengan jumlah setor.",
            "recommendation": "Klarifikasi ke Divisi Keuangan, bukan ke MBX; cek kemungkinan salah input, double input, atau nominal setor tidak sesuai.",
            "clarification_required": True,
        },
        "split_txn": {
            "category": "Indikator Nilai Transaksi",
            "name": "Nominal tidak wajar atau indikasi splitting",
            "definition": "Nominal tidak wajar atau pemecahan transaksi/setoran tanpa alasan jelas menjadi indikator risiko.",
            "description": "Ada pola transaksi kecil berdekatan atau nominal tidak wajar.",
            "recommendation": "Cek apakah pemecahan transaksi memiliki alasan sah dan dokumen pendukung.",
            "clarification_required": True,
        },
    },
}
