RULE_CONFIG = {
    "risk_level": {"low_max": 3, "medium_max": 7},
    "attention_window": {
        "start_hour": 0,
        "end_hour": 5,
        "start_minute": 1,
        "end_minute": 300,
        "label": "00:01-05:00",
    },
    "late_input_max_days": 2,
    "late_input_score": {
        "transfer": {"low_after_days": 3, "medium_after_days": 4, "high_after_days": 8, "critical_after_days": 11, "low_score": 1, "medium_score": 2, "high_score": 4, "critical_score": 8},
        "tunai": {"low_after_days": 3, "medium_after_days": 4, "high_after_days": 8, "critical_after_days": 11, "low_score": 1, "medium_score": 2, "high_score": 4, "critical_score": 8},
    },
    "holidays": {
        # SKB 3 Menteri: Libur Nasional dan Cuti Bersama Indonesia 2026.
        "2026-01-01": "Tahun Baru 2026 Masehi",
        "2026-01-16": "Isra Mikraj Nabi Muhammad saw.",
        "2026-02-16": "Cuti Bersama Tahun Baru Imlek 2577 Kongzili",
        "2026-02-17": "Tahun Baru Imlek 2577 Kongzili",
        "2026-03-18": "Cuti Bersama Hari Suci Nyepi",
        "2026-03-19": "Hari Suci Nyepi Tahun Baru Saka 1948",
        "2026-03-20": "Cuti Bersama Idulfitri 1447 H",
        "2026-03-21": "Idulfitri 1447 H",
        "2026-03-22": "Idulfitri 1447 H",
        "2026-03-23": "Cuti Bersama Idulfitri 1447 H",
        "2026-03-24": "Cuti Bersama Idulfitri 1447 H",
        "2026-04-03": "Wafat Yesus Kristus",
        "2026-04-05": "Kebangkitan Yesus Kristus (Paskah)",
        "2026-05-01": "Hari Buruh Internasional",
        "2026-05-14": "Kenaikan Yesus Kristus",
        "2026-05-15": "Cuti Bersama Kenaikan Yesus Kristus",
        "2026-05-27": "Iduladha 1447 H",
        "2026-05-28": "Cuti Bersama Iduladha 1447 H",
        "2026-05-31": "Hari Raya Waisak 2570 BE",
        "2026-06-01": "Hari Lahir Pancasila",
        "2026-06-16": "1 Muharam Tahun Baru Islam 1448 H",
        "2026-08-17": "Proklamasi Kemerdekaan",
        "2026-08-25": "Maulid Nabi Muhammad saw.",
        "2026-12-24": "Cuti Bersama Kelahiran Yesus Kristus",
        "2026-12-25": "Kelahiran Yesus Kristus",
    },
    "amount_tolerance": 0.0,
    "score": {
        "off_hour": 1,
        "pre_payment_input": 2,
        "late_input_transfer": 2,
        "late_input_cash": 2,
        "date_mismatch": 1,
        "amount_mismatch": 4,
        "double_input": 5,
    },
    "rules": {
        "off_hour": {
            "category": "Indikator Waktu",
            "name": "Input transaksi pada rentang waktu tertentu",
            "definition": "Penginputan transaksi pada rentang waktu tertentu perlu menjadi perhatian khusus sesuai matriks skor FEWS.",
            "description": "Input pada jam tidak normal menjadi perhatian khusus.",
            "recommendation": "Klarifikasi alasan input di rentang waktu perhatian dan pertimbangkan pembatasan input pada jam tertentu.",
            "clarification_required": True,
        },
        "pre_payment_input": {
            "category": "Indikator Waktu",
            "name": "Input sebelum transfer terjadi",
            "definition": "Penginputan transaksi harus dilakukan setelah pembayaran/transfer diterima.",
            "description": "Input mendahului tanggal/waktu pembayaran atau transfer.",
            "recommendation": "Minta bukti transfer dan koreksi tanggal input jika terjadi kesalahan.",
            "clarification_required": True,
        },
        "late_input_transfer": {
            "category": "Indikator Waktu",
            "name": "Keterlambatan input data setor transfer",
            "definition": "Input maksimal H+2 hari kerja dari tanggal bank. Keterlambatan mulai H+3, lalu dinilai bertingkat: H+3, H+4-H+7, H+8-H+10, dan lebih dari H+10 sebagai warning merah.",
            "description": "Input transfer lebih dari H+2 hari kerja dari tanggal bank.",
            "recommendation": "Klarifikasi penyebab keterlambatan transfer dan dokumentasikan pengecualian hari libur/bank tutup jika ada.",
            "clarification_required": True,
        },
        "late_input_cash": {
            "category": "Indikator Waktu",
            "name": "Keterlambatan input setoran tunai ke bank",
            "definition": "Input maksimal H+2 hari kerja dari tanggal bank. Keterlambatan mulai H+3, lalu dinilai bertingkat: H+3, H+4-H+7, H+8-H+10, dan lebih dari H+10 sebagai warning merah.",
            "description": "Input setoran tunai lebih dari H+2 hari kerja dari tanggal bank.",
            "recommendation": "Klarifikasi tanggal setor tunai ke bank dan alasan keterlambatan input.",
            "clarification_required": True,
        },
        "date_mismatch": {
            "category": "Indikator Waktu",
            "name": "Tanggal tidak konsisten pada data setoran",
            "definition": "Tanggal input dan tanggal setor harus konsisten.",
            "description": "Tanggal input dan tanggal setor tidak selaras.",
            "recommendation": "Bandingkan tanggal input dengan tanggal setor dan lakukan koreksi melalui mekanisme audit trail.",
            "clarification_required": True,
        },
        "amount_mismatch": {
            "category": "Indikator Nilai Transaksi",
            "name": "Jumlah biaya tidak sesuai jumlah setor",
            "definition": "Jumlah biaya pada SIL harus sesuai dengan jumlah setor; selisih dapat mengindikasikan salah input atau double input.",
            "description": "Jumlah biaya berbeda dengan jumlah setor.",
            "recommendation": "Klarifikasi ke Divisi Keuangan, bukan ke MBX; cek kemungkinan salah input, double input, atau nominal setor tidak sesuai.",
            "clarification_required": True,
        },
        "double_input": {
            "category": "Indikator Duplikasi Transaksi",
            "name": "Double Input Bukti Transfer",
            "definition": "Data aktif dengan nomor bukti, nominal, tanggal transaksi, jenis transaksi, dan lokasi yang sama terindikasi sebagai input ganda meskipun ID Unix atau metadata lainnya berbeda.",
            "description": "Data transaksi dan bukti transfer yang sama ditemukan lebih dari satu kali.",
            "recommendation": "Periksa bukti transfer dan ID Unix terkait, lalu arsipkan entri duplikat melalui mekanisme koreksi agar audit trail tetap terjaga.",
            "clarification_required": True,
        },
    },
}
